version: '3'
services:
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    volumes:
      - "./mysql/default_authentication.cnf:/etc/mysql/conf.d/default_authentication.cnf"
      - "./mysql/dev-data:/var/lib/mysql"
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_NAME_DEV}

  test-db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    volumes:
      - "./mysql/default_authentication.cnf:/etc/mysql/conf.d/default_authentication.cnf"
      - "./mysql/test-data:/var/lib/mysql"
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_NAME_TEST}

  app:
    build:
      context: ./code
      dockerfile: Dockerfile
    volumes:
      - "./code:/var/www"
    ports:
      - "${APP_PORT}:3000"
    environment:
      RAILS_ENV: development
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_NAME_DEV: ${MYSQL_NAME_DEV}
      MYSQL_NAME_TEST: ${MYSQL_NAME_TEST}
      MYSQL_NAME: ${MYSQL_NAME}
    depends_on:
      - db
      - test-db
    tty: true
    restart: always
