default: &default
  adapter: mysql2
  host: <%= ENV['MYSQL_HOST'] %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['MYSQL_NAME_DEV'] %>

test:
  <<: *default
  database: <%= ENV['MYSQL_NAME_TEST'] %>

production:
  <<: *default
  database: <%= ENV['MYSQL_NAME'] %>